// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tanjujeyzcpwcsxiainc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhbmp1amV5emNwd2NzeGlhaW5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyMTg2MjYsImV4cCI6MjA1MDc5NDYyNn0.jqbTWuf2SrkoPbY9fLzOY0wGCb1i5w_7kytQp99Sf9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);